apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sshd-config
  namespace: {{ .Values.namespace }}
data:
  sshd_config: |-
    Include /etc/ssh/sshd_config.d/*.conf
    KbdInteractiveAuthentication no
    UsePAM yes
    X11Forwarding no
    PasswordAuthentication no
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem	sftp	/usr/lib/openssh/sftp-server

{{- range $name, $key := .Values.sshd.host_keys }}
  ssh_host_{{ $name }}_key: {{ $key }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-access-config
data:
  authorized_keys: |-
    {{- range $key := .Values.sshd.authorized_keys }}
      {{ $key }}
    {{- end }}
