apiVersion: apps/v1
kind: Deployment
metadata:
  name: kadalu-backup-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: kadalu-backup
spec:
  selector:
    matchLabels:
      app: kadalu-backup
  template:
    metadata:
      labels:
        app: kadalu-backup
    spec:
      containers:
      - name: kadalu-backup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
          - "--host"
          - "{{ .Values.pool_name }}"
          - "--name"
          - "{{ .Values.pool_name }}"
        securityContext:
          privileged: true
        volumeMounts:
        - name: sshd-config
          mountPath: /etc/ssh/sshd_config
          subPath: sshd_config
      {{- range $name, $key := .Values.sshd.host_keys }}
        - name: sshd-config
          mountPath: /etc/ssh/ssh_host_{{ $name }}_key
          subPath: ssh_host_{{ $name }}_key
      {{- end }}
        - name: access-config
          mountPath: /home/kadalu/.ssh/authorized_keys
          subPath: authorized_keys
        - name: fuse
          mountPath: /dev/fuse
        resources:
          requests:
            memory: "128Mi"
      volumes:
      - name: fuse
        hostPath:
          path: /dev/fuse
      - name: sshd-config
        configMap:
          name: {{ .Release.Name }}-sshd-config
          defaultMode: 0600
      - name: access-config
        configMap:
          name: {{ .Release.Name }}-access-config
          defaultMode: 0600
