apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sshd-keys
  namespace: {{ .Values.namespace }}
data:
{{- range $name, $key := .Values.sshd.host_keys }}
  ssh_host_{{ $name }}_key: {{ $key }}
{{- end }}
