apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kadalu-backup
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: {{ .Values.service.type }}
