# Default values for hostapd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/koskev/kadalu-backup
  pullPolicy: IfNotPresent
  tag: "2023.11.22"

namespace: "kadalu"
pool_name: "arbiter-pool"

service:
  type: LoadBalancer

sshd:
  # Complete content of your id_rsa.pub
  authorized_keys: []

  # Name and entries in a secret
  host_key_secret: {}
  #  name: "kadalu-backup-keys"
  #  keys:
  #    - ed25519
